application: your-application-id-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /web
  static_dir: web

- url: /tasks/*
  script: app.app
  login: admin

- url: .*
  script: app.app

env_variables:
  BOT_USERNAME: 'botapitest'
  BOT_API_KEY: 'fec01e78-6cc4-4b2a-96bf-555ac1c5d075'
  MIXPANEL_TOKEN: 'foo'

libraries:
- name: ssl
  version: latest

inbound_services:
- warmup
