application: your-application-id-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /web
  static_dir: web

- url: .*
  script: app.app

env_variables:
  BOT_USERNAME: 'your-bot-username-here'
  BOT_API_KEY: 'your-api-key-here'

libraries:
- name: ssl
  version: latest

inbound_services:
- warmup
