application: your-application-id-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /web
  static_dir: web

- url: /tasks/*
  script: app.app
  login: admin

- url: .*
  script: app.app

env_variables:
  BOT_USERNAME: 'mrworldwidebot'
  BOT_API_KEY: '0a4ca262-4274-424f-ab9e-4666e0d0751b'
  MIXPANEL_TOKEN: 'asd'

libraries:
- name: ssl
  version: latest

inbound_services:
- warmup
